"""add_expanded_scorecard_fields

Revision ID: 034d54eea16f
Revises: 
Create Date: 2026-03-26 20:10:55.359632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '034d54eea16f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('gpa', sa.String(length=20), nullable=True),
    sa.Column('major', sa.String(length=255), nullable=True),
    sa.Column('biggest_worry', sa.Text(), nullable=True),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('top_match_1', sa.String(length=255), nullable=True),
    sa.Column('top_match_2', sa.String(length=255), nullable=True),
    sa.Column('top_match_3', sa.String(length=255), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.add_column('schools', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('school_url', sa.String(length=500), nullable=True))
    op.add_column('schools', sa.Column('price_calculator_url', sa.String(length=500), nullable=True))
    op.add_column('schools', sa.Column('alias', sa.String(length=255), nullable=True))
    op.add_column('schools', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('schools', sa.Column('zip_code', sa.String(length=10), nullable=True))
    op.add_column('schools', sa.Column('men_only', sa.Boolean(), nullable=True))
    op.add_column('schools', sa.Column('women_only', sa.Boolean(), nullable=True))
    op.add_column('schools', sa.Column('online_only', sa.Boolean(), nullable=True))
    op.add_column('schools', sa.Column('open_admissions', sa.Boolean(), nullable=True))
    op.add_column('schools', sa.Column('carnegie_basic', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('carnegie_size_setting', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('faculty_salary', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('ft_faculty_rate', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('tuition_revenue_per_fte', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('instructional_expenditure_per_fte', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('book_supply_cost', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('avg_net_price', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('other_expense_oncampus', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('cost_of_attendance', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('pell_grant_rate', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('federal_loan_rate', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('median_debt', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('median_debt_monthly_payment', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('students_with_any_loan', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('demographics_men', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('demographics_women', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('avg_age_entry', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('first_generation_rate', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('median_family_income', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('part_time_share', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('grad_students', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('fafsa_applications', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('earnings_6yr_after_entry', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('earnings_8yr_after_entry', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('earnings_1yr_after_completion', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('earnings_4yr_after_completion', sa.Integer(), nullable=True))
    op.add_column('schools', sa.Column('completion_rate_4yr_100', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('completion_rate_4yr_200', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('transfer_rate_4yr_ft', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('consumer_rate', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('programs_offered', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'programs_offered')
    op.drop_column('schools', 'consumer_rate')
    op.drop_column('schools', 'transfer_rate_4yr_ft')
    op.drop_column('schools', 'completion_rate_4yr_200')
    op.drop_column('schools', 'completion_rate_4yr_100')
    op.drop_column('schools', 'earnings_4yr_after_completion')
    op.drop_column('schools', 'earnings_1yr_after_completion')
    op.drop_column('schools', 'earnings_8yr_after_entry')
    op.drop_column('schools', 'earnings_6yr_after_entry')
    op.drop_column('schools', 'fafsa_applications')
    op.drop_column('schools', 'grad_students')
    op.drop_column('schools', 'part_time_share')
    op.drop_column('schools', 'median_family_income')
    op.drop_column('schools', 'first_generation_rate')
    op.drop_column('schools', 'avg_age_entry')
    op.drop_column('schools', 'demographics_women')
    op.drop_column('schools', 'demographics_men')
    op.drop_column('schools', 'students_with_any_loan')
    op.drop_column('schools', 'median_debt_monthly_payment')
    op.drop_column('schools', 'median_debt')
    op.drop_column('schools', 'federal_loan_rate')
    op.drop_column('schools', 'pell_grant_rate')
    op.drop_column('schools', 'cost_of_attendance')
    op.drop_column('schools', 'other_expense_oncampus')
    op.drop_column('schools', 'avg_net_price')
    op.drop_column('schools', 'book_supply_cost')
    op.drop_column('schools', 'instructional_expenditure_per_fte')
    op.drop_column('schools', 'tuition_revenue_per_fte')
    op.drop_column('schools', 'ft_faculty_rate')
    op.drop_column('schools', 'faculty_salary')
    op.drop_column('schools', 'carnegie_size_setting')
    op.drop_column('schools', 'carnegie_basic')
    op.drop_column('schools', 'open_admissions')
    op.drop_column('schools', 'online_only')
    op.drop_column('schools', 'women_only')
    op.drop_column('schools', 'men_only')
    op.drop_column('schools', 'zip_code')
    op.drop_column('schools', 'address')
    op.drop_column('schools', 'alias')
    op.drop_column('schools', 'price_calculator_url')
    op.drop_column('schools', 'school_url')
    op.drop_column('schools', 'longitude')
    op.drop_column('schools', 'latitude')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
